
        /*
         * MIT License
         *
         * Copyright (c) 2020 Jannis Weis
         *
         * Permission is hereby granted, free of charge, to any person obtaining a copy
         * of this software and associated documentation files (the "Software"), to deal
         * in the Software without restriction, including without limitation the rights
         * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
         * copies of the Software, and to permit persons to whom the Software is
         * furnished to do so, subject to the following conditions:
         *
         * The above copyright notice and this permission notice shall be included in all
         * copies or substantial portions of the Software.
         *
         * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
         * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
         * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
         * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
         * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
         * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
         * SOFTWARE.
         *
         */

        import javax.swing.*;

        import com.github.weisj.darklaf.util.DarkUIUtil;

public class DemoResources {
    public static final String LOREM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempor quis nibh a semper. Nullam\n"
            + " auctor, erat non viverra commodo, libero orci aliquam quam, ac interdum nunc est sed\n "
            + "ligula. Aliquam vel velit non dolor accumsan blandit id eu metus. Aenean iaculis urna in\n "
            + "placerat aliquam. Aliquam dui quam, bibendum sed magna in, cursus ornare est. Quisque\n "
            + "tempor nunc quis nunc tempor convallis. Vestibulum tristique luctus ante, ac hendrerit dui.\n\n"
            + "Donec ut maximus augue. Nam eleifend maximus scelerisque. Duis varius accumsan est, non\n "
            + "aliquam dolor. Aenean iaculis nibh in aliquam viverra. Sed laoreet, urna ut facilisis\n "
            + "convallis, arcu turpis vestibulum augue, id convallis tellus metus nec orci. Lorem ipsum\n "
            + "dolor sit amet, consectetur adipiscing elit. Donec hendrerit purus velit, at blandit elit\n "
            + "luctus ut. Proin diam nisl, sodales vitae dignissim nec, eleifend eu libero. Maecenas odio\n"
            + " ligula, fermentum eget nisl vel, cursus tristique est. In nec nibh nec dui tempor\n "
            + "ullamcorper. Praesent tincidunt luctus sem, ut luctus dolor commodo non. Nulla consectetur\n"
            + " facilisis dolor, in facilisis ligula fringilla et. Cras id placerat libero. Donec\n "
            + "vehicula orci a quam rutrum, eu efficitur lorem iaculis. Aenean varius nisi in dictum\n "
            + "accumsan.\n\n"
            + "Nulla massa ipsum, consectetur non gravida ut, blandit quis velit. Ut pretium quam aliquam\n"
            + " diam porttitor mattis. Nam ullamcorper, felis ut iaculis iaculis, nunc odio pulvinar \n"
            + "enim, vitae iaculis turpis sapien iaculis metus. Donec rutrum varius augue in dictum. Cras\n"
            + " vestibulum vitae mauris ut finibus. Ut dictum imperdiet lorem et imperdiet. Vivamus \n"
            + "semper tempor dolor eu porta. Sed at vehicula nisl. Pellentesque ut lorem tincidunt, \n"
            + "elementum ligula at, porta turpis. Praesent feugiat dolor diam, at facilisis metus gravida\n"
            + " non. Aliquam quis pellentesque nibh. Sed vestibulum porttitor nisi. In vitae malesuada\n "
            + "sapien.";
    public static final String HTML_DEMO = "<h1>Lorem ipsum dolor sit amet consectetuer adipiscing \n"
            + "elit</h1>\n"
            + "\n"
            + "\n"
            + "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing \n"
            + "elit. Aenean commodo ligula eget dolor. Aenean massa \n"
            + "<strong>strong</strong>. Cum sociis natoque penatibus \n"
            + "et magnis dis parturient montes, nascetur ridiculus \n"
            + "mus. Donec quam felis, ultricies nec, pellentesque \n"
            + "eu, pretium quis, sem. Nulla consequat massa quis \n"
            + "enim. Donec pede justo, fringilla vel, aliquet nec, \n"
            + "vulputate eget, arcu. In enim justo, rhoncus ut, \n"
            + "imperdiet a, venenatis vitae, justo. Nullam dictum \n"
            + "felis eu pede <a class=\"external ext\" href=\"#\">link</a> \n"
            + "mollis pretium. Integer tincidunt. Cras dapibus. \n"
            + "Vivamus elementum semper nisi. Aenean vulputate \n"
            + "eleifend tellus. Aenean leo ligula, porttitor eu, \n"
            + "consequat vitae, eleifend ac, enim. Aliquam lorem ante, \n"
            + "dapibus in, viverra quis, feugiat a, tellus. Phasellus \n"
            + "viverra nulla ut metus varius laoreet. Quisque rutrum. \n"
            + "Aenean imperdiet. Etiam ultricies nisi vel augue. \n"
            + "Curabitur ullamcorper ultricies nisi.</p>\n"
            + "\n"
            + "\n"
            + "<h1>Lorem ipsum dolor sit amet consectetuer adipiscing \n"
            + "elit</h1>\n"
            + "\n"
            + "\n"
            + "<h2>Aenean commodo ligula eget dolor aenean massa</h2>\n"
            + "\n"
            + "\n"
            + "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing \n"
            + "elit. Aenean commodo ligula eget dolor. Aenean massa. \n"
            + "Cum sociis natoque penatibus et magnis dis parturient \n"
            + "montes, nascetur ridiculus mus. Donec quam felis, \n"
            + "ultricies nec, pellentesque eu, pretium quis, sem.</p>\n"
            + "\n"
            + "\n"
            + "<h2>Aenean commodo ligula eget dolor aenean massa</h2>\n"
            + "\n"
            + "\n"
            + "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing \n"
            + "elit. Aenean commodo ligula eget dolor. Aenean massa. \n"
            + "Cum sociis natoque penatibus et magnis dis parturient \n"
            + "montes, nascetur ridiculus mus. Donec quam felis, \n"
            + "ultricies nec, pellentesque eu, pretium quis, sem.</p>\n"
            + "\n"
            + "\n"
            + "<ul>\n"
            + "  <li>Lorem ipsum dolor sit amet consectetuer.</li>\n"
            + "  <li>Aenean commodo ligula eget dolor.</li>\n"
            + "  <li>Aenean massa cum sociis natoque penatibus.</li>\n"
            + "</ul>\n"
            + "\n"
            + "hr:"
            + "<hr></hr>"
            + "\n"
            + "custom div:"
            + "<div style=\"height: 0px; border-top-style: solid; border-width: 1px\"></div>"
            + "\n"
            + "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing \n"
            + "elit. Aenean commodo ligula eget dolor. Aenean massa. \n"
            + "Cum sociis natoque penatibus et magnis dis parturient \n"
            + "montes, nascetur ridiculus mus. Donec quam felis, \n"
            + "ultricies nec, pellentesque eu, pretium quis, sem.</p>\n"
            + "\n"
            + "\n"
            + "<form action=\"#\" method=\"post\">\n"
            + "  <fieldset>\n"
            + "    <label for=\"name\">Name:</label>\n"
            + "    <input type=\"text\" id=\"name\" placeholder=\"Enter your \n"
            + "full name\" />\n"
            + "\n"
            + "    <label for=\"email\">Email:</label>\n"
            + "    <input type=\"email\" id=\"email\" placeholder=\"Enter \n"
            + "your email address\" />\n"
            + "\n"
            + "    <label for=\"message\">Message:</label>\n"
            + "    <textarea id=\"message\" placeholder=\"What's on your \n"
            + "mind?\"></textarea>\n"
            + "\n"
            + "    <input type=\"submit\" value=\"Send message\" />\n"
            + "\n"
            + "  </fieldset>\n"
            + "</form>\n"
            + "\n"
            + "\n"
            + "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing \n"
            + "elit. Aenean commodo ligula eget dolor. Aenean massa. \n"
            + "Cum sociis natoque penatibus et magnis dis parturient \n"
            + "montes, nascetur ridiculus mus. Donec quam felis, \n"
            + "ultricies nec, pellentesque eu, pretium quis, sem.</p>\n"
            + "\n"
            + "\n"
            + "<table class=\"data\">\n"
            + "  <tr>\n"
            + "    <th>Entry Header 1</th>\n"
            + "    <th>Entry Header 2</th>\n"
            + "    <th>Entry Header 3</th>\n"
            + "    <th>Entry Header 4</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <td>Entry First Line 1</td>\n"
            + "    <td>Entry First Line 2</td>\n"
            + "    <td>Entry First Line 3</td>\n"
            + "    <td>Entry First Line 4</td>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <td>Entry Line 1</td>\n"
            + "    <td>Entry Line 2</td>\n"
            + "    <td>Entry Line 3</td>\n"
            + "    <td>Entry Line 4</td>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <td>Entry Last Line 1</td>\n"
            + "    <td>Entry Last Line 2</td>\n"
            + "    <td>Entry Last Line 3</td>\n"
            + "    <td>Entry Last Line 4</td>\n"
            + "  </tr>\n"
            + "</table>\n"
            + "\n"
            + "\n"
            + "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing \n"
            + "elit. Aenean commodo ligula eget dolor. Aenean massa. \n"
            + "Cum sociis natoque penatibus et magnis dis parturient \n"
            + "montes, nascetur ridiculus mus. Donec quam felis, \n"
            + "ultricies nec, pellentesque eu, pretium quis, sem.</p>\n";
    public static final String KERNING_TEST = "Basic Kerning Text\n"
            + "\n"
            + "\n"
            + "BASIC ALPHABET \n"
            + "\n"
            + "AÆBCÇDEFGH\n"
            + "IJKLMNOŒØP\n"
            + "QRSTUVWXYZ/\\\n"
            + "jhbjhbhjb\n"
            + "noœøpqrstuvwxyz\n"
            + "1234567890\n"
            + "HlHmHnHoHpHqHrHsHtHuH\n"
            + "HvHwHxHyHzHßHæHœHäH\n"
            + "dndodpdqdrdsdtdudvdwdxdydzd\n"
            + "Ií Iì Iî Iï \n"
            + "Jacky Jester Jimmy Joint Junk  \n"
            + "Jí Jì Jî Jï\n"
            + "Kangaroo Keep Kill Kline\n"
            + "Kop Kudees Kwick Kva Kyle \n"
            + "Kärn Köff Küdos Kì Kî Kï Kÿ\n"
            + "Lay Learned Listing Load Lung\n"
            + "Lw Lynch \n"
            + "Mail Meal Minx Mode Music \n"
            + "Myth Mí Mì Mî Mï\n"
            + "Nail Next Nile Nooky Numb \n"
            + "Ní Nì Nî Nï\n"
            + "Oatmeal Oer Offer Ogor Oink Oolong \n"
            + "Out Over Oyster Oí Oì Oî Oï\n"
            + "Painter Peal Pile Pıne Pjb Plaster\n"
            + "Pointer Printer Putt Pygmy Päl Pöl\n"
            + "Pünk Pál Pà Pâl Pãl På Pél Pè \n"
            + "Pêl Píl Pì Pîl Pïl Pól Pò Pôl\n"
            + "Põl Púl Pù Pûl Pÿ\n"
            + "Qanat Qels Qix Qon Quest \n"
            + "Qí Qì Qî Qï\n"
            + "Rate Red Right Royal Run \n"
            + "Ryal Rän Röad Rüng\n"
            + "Rí Rì Rî Rï\n"
            + "Sallie Scuzz Sensation Shell Sink \n"
            + "Smelly Snowball Soul Spoke Sqish \n"
            + "Stoner Sung Svelt Swap Symantic\n"
            + "Sí Sì Sî Sï\n"
            + "Tail Teal Them Timer Tıme \n"
            + "Toll Trustee Tsing Tumbs Twizzlers\n"
            + "Typing Täp Törn Tüff Tál Tà Tâl \n"
            + "Tãl Tål Tél Tè Têl Tël Tíl Tì Tîl \n"
            + "Tïl Tól Tò Tôl Tõl Túl Tù Tûl Tÿ\n"
            + "Uarco Ue Ui Umbrella Under Uo \n"
            + "Upper Ursula User Utterly Uu Uv \n"
            + "Uwe Uí Uì Uî Uï\n"
            + "Vain Vc Veto Vine Vıne Vlad\n"
            + "Vow Vroor Vs Vulgar Vying \n"
            + "Vämping Vöter Vál Và Vâl Vãl Vå \n"
            + "Vél Vè Vêl Vë Víl Vìl Vîl Vïl Vól \n"
            + "Vò Vôl Vö Võl Vúl Vù Vûl Vü Vÿ\n"
            + "Wale Wet What Window Wınd \n"
            + "Wm Wow Wren Wsa Wte Wud \n"
            + "Wxe Wynde Wäne Wál Wà Wâl\n"
            + "Wãl Wå Wél Wè Wêl Wël Wíl \n"
            + "Wìl Wîl Wïl Wól Wò Wôl Wöl \n"
            + "Wÿ Wõl Wúl Wù Wûl Wül\n"
            + "Xanth Xelo Xi Xo Xu Xylo \n"
            + "Xál Xà Xâ Xä Xã Xå Xé Xè\n"
            + "Xê Xë Xíl Xìl Xîl Xïl Xó Xò Xô \n"
            + "Xö Xõ Xú Xù Xû Xü Xå Xÿ\n"
            + "Yale Yddes Yearling Yicks Yıeld \n"
            + "Yoyo Ypring Yrs Ys Yuck \n"
            + "Yviye Yz Yá Yà Yâ Yä Yã Yå \n"
            + "Yé Yè Yê Yë Yí Yì Yî Yï Yó \n"
            + "Yò Yô Yö Yõ Yú Yù Yû Yü  \n"
            + "Zanzabar Zellis Zion Zope Zulu \n"
            + "Zyle Zí Zì Zî Zï\n"
            + "\n"
            + "\n"
            + "SIDE BEARINGS\n"
            + "\n"
            + "HIHOH\n"
            + "HAHBHCHDHEH\n"
            + "OAOBOCODOEO\n"
            + "HFHGHHHIHJH\n"
            + "OFOGOHOIOJO\n"
            + "HKHLHMHNHOHPHON\n"
            + "OKOLOMONOOPO\n"
            + "HQUHRHSHTHUH\n"
            + "OQOROSOTOUO\n"
            + "HVHWHXHYHZH\n"
            + "OVOWOXOYOZO\n"
            + "\n"
            + "\n"
            + "LOWER CASE & PUNCTUATION\n"
            + "\n"
            + "H…H. H! H?\n"
            + "l…l. l: l, l; l! l?\n"
            + "a…a. a: a, a; a! a?\n"
            + "b…b. b: b, b; b! b?\n"
            + "c…c. c: c, c; c! c?\n"
            + "d…d. d: d, d; d! d?\n"
            + "e…e. e: e, e; e! e?\n"
            + "f…f. f: f, f; f! f?\n"
            + "g…g. g: g, g; g! g?\n"
            + "h…h. h: h, h; h! h?\n"
            + "i…i. i: i, i; i! i?\n"
            + "j…j. j: j, j; j! j?\n"
            + "k…k. k: k, k; k! k?\n"
            + "l…l. l: l, l; l! l?\n"
            + "m…m. m: m, m; m! m?\n"
            + "n…n. n: n, n; n! n?\n"
            + "o…o. o: o, o; o! o?\n"
            + "p…p. p: p, p; p! p?\n"
            + "q…q. q: q, q; q! q?\n"
            + "r…r. r: r, r; r! r?\n"
            + "s…s. s: s, s; s! s?\n"
            + "t…t. t: t, t; t! t?\n"
            + "u…u. u: u, u; u! u?\n"
            + "v…v. v: v, v; v! v?\n"
            + "w…w. w: w, w; w! w?\n"
            + "x…x. x: x, x; x! x?\n"
            + "y…y. y: y, y; y! y?\n"
            + "z…z. z: z, z; z! z?\n"
            + "\n";
}

